[package]
name = "counter-client"
version = "0.1.0"
authors = ["ve"]

[dependencies]
clippy = {version = "0.0.172", optional = true}

tokio-core = "0.1.10"
tokio-io = "0.1.4"
futures = "0.1.17"
futures-cpupool = "0.1.7"
rand = "0.3"

[features]
default = []
dev = ["clippy"]
